baseURL = 'https://rafamsa.github.io/'
locale = 'pt-br'
title = 'Rafael Martins'
enableRobotsTXT = true
canonifyURLs = true

theme = "terminal"
defaultContentLanguage = 'pt-br'
defaultContentLanguageInSubdir = false
disableDefaultLanguageRedirect = false
disableLanguages = []

[params]
author = "Rafael Martins da Silva Afeto"
description = "Um blog sobre ciência, educação, arte e cultura."
centerTheme = true
showMenuItems = 6
readMore = "Leia mais"
newerPosts = "Artigos mais recentes"
olderPosts = "Artigos mais antigos"
customCSS = ["css/extended.css"]
showLanguageSelector = true

# SEO
subtitle = "Blog de divulgação científica, educação, arte e cultura por Rafael Martins — UNIFAL-MG"
keywords = [
    "divulgação científica",
    "ciência",
    "educação",
    "UNIFAL-MG",
    "pesquisa acadêmica",
    "arte e cultura",
]


[params.Logo]
logoText = "Rafael Martins"

[[menus.main]]
name = "Artigos"
url = "/posts/"
weight = 10

[[menus.main]]
name = "Educação"
url = "/edu/"
weight = 20

[[menus.main]]
name = "Ilustrações"
url = "/ilustracoes/"
weight = 30

[[menus.main]]
name = "Categorias"
url = "/categories/"
weight = 40

[[menus.main]]
name = "Assuntos"
url = "/tags/"
weight = 50

[[menus.main]]
name = "Quem sou"
url = "/quem-sou/"
weight = 60

[languages]
[languages.pt-br]
label = 'PT'
locale = 'pt-br'
weight = 1
title = 'Rafael Martins :: Divulgação científica, educação, arte e cultura'

[languages.en]
label = 'EN'
locale = 'en-US'
weight = 2
title = 'Rafael Martins'
fallback = ['pt-br']

[[languages.en.menus.main]]
name = "Articles"
url = "/en/posts/"
weight = 10

[[languages.en.menus.main]]
name = "Education"
url = "/en/edu/"
weight = 20

[[languages.en.menus.main]]
name = "Illustrations"
url = "/en/ilustracoes/"
weight = 30

[[languages.en.menus.main]]
name = "Categories"
url = "/en/categories/"
weight = 40

[[languages.en.menus.main]]
name = "Topics"
url = "/en/tags/"
weight = 50

[[languages.en.menus.main]]
name = "About me"
url = "/en/quem-sou/"
weight = 60


[languages.es]
label = 'ES'
locale = 'es-ES'
weight = 3
title = 'Rafael Martins'
fallback = ['pt-br']

[[languages.es.menus.main]]
name = "Artículos"
url = "/es/posts/"
weight = 10

[[languages.es.menus.main]]
name = "Educación"
url = "/es/edu/"
weight = 20

[[languages.es.menus.main]]
name = "Ilustraciones"
url = "/es/ilustracoes/"
weight = 30

[[languages.es.menus.main]]
name = "Categorías"
url = "/es/categories/"
weight = 40

[[languages.es.menus.main]]
name = "Temas"
url = "/es/tags/"
weight = 50

[[languages.es.menus.main]]
name = "Sobre mí"
url = "/es/quem-sou/"
weight = 60
