baseURL = 'https://rafamsa.github.io/meu_blog/'
locale = 'pt-br'
title = 'My New Hugo Project'

theme = "terminal"

[languages]
[languages.pt-br]
languageName = 'Portuguese'
title = 'Meu Novo Projeto Hugo'
