baseURL = 'https://rafamsa.github.io/meu_blog/'
locale = 'pt-br'
title = 'My New Hugo Project'

theme = "terminal"

[params]
author = "Rafael M. S. A."
description = "A blog about programming, technology, and more."
centerTheme = true
showMenuItems = 4

[params.Logo]
logoText = "Meu Blog"

[[menus.main]]
name = "Bio"
url = "/bio/"
weight = 10

[[menus.main]]
name = "Posts"
url = "/posts/"
weight = 20

[[menus.main]]
name = "Tags"
url = "/tags/"
weight = 30

[languages]
[languages.pt-br]
languageName = 'Portuguese'
title = 'Meu Novo Projeto Hugo'
